// Brand kit: every logo variant in every colorway as SVG and PNG, plus the
// tokens as CSS, Tailwind, DTCG JSON and TypeScript. Pure Node (resvg for
// rasterizing), so it runs in CI without a browser.

import { Resvg } from "@resvg/resvg-js";
import { strToU8, zipSync } from "fflate";
import { existsSync, mkdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import type { BrandInput } from "../shared/brand-schema.ts";
import { colorwayHex, composeLogo, logoVariants } from "../shared/lockup.ts";
import { tailwindCss, tokensCss, tokensJson } from "../shared/tokens.ts";

export const PNG_HEIGHTS = [128, 512] as const;

export interface KitFile {
  path: string;
  data: Uint8Array;
}

export interface BuildKitOptions {
  brand: BrandInput;
  svgs: Record<string, string>;
  brandAssetsDir: string;
  version?: string;
}

function rasterize(svg: string, height: number): Uint8Array {
  const r = new Resvg(svg, { fitTo: { mode: "height", value: height }, background: "rgba(0,0,0,0)" });
  return r.render().asPng();
}

export function buildBrandKit(opts: BuildKitOptions): KitFile[] {
  const { brand, svgs } = opts;
  const files: KitFile[] = [];
  const add = (path: string, data: string | Uint8Array) => files.push({ path, data: typeof data === "string" ? strToU8(data) : data });

  const logoRows: string[] = [];
  for (const variant of logoVariants(brand)) {
    for (const colorway of Object.keys(brand.logo.colorways)) {
      const { svg } = composeLogo(brand, svgs, variant, colorwayHex(brand, colorway));
      const base = `logos/${variant}/${variant}-${colorway}`;
      add(`${base}.svg`, svg + "\n");
      for (const h of PNG_HEIGHTS) add(`${base}-${h}.png`, rasterize(svg, h));
      logoRows.push(`| ${variant} | ${colorway} | [svg](${base}.svg) | ${PNG_HEIGHTS.map((h) => `[${h}px](${base}-${h}.png)`).join(" ")} |`);
    }
  }

  add("tokens/tokens.css", tokensCss(brand));
  add("tokens/tailwind.css", tailwindCss(brand));
  add("tokens/tokens.json", JSON.stringify(tokensJson(brand), null, 2) + "\n");
  add("tokens/brand.ts", `// ${brand.name} brand, generated by ided. Do not edit.\nexport const brand = ${JSON.stringify(brand, null, 2)} as const;\n`);

  for (const font of Object.values(brand.font)) {
    for (const f of font.files ?? []) {
      const src = join(opts.brandAssetsDir, f.src);
      if (existsSync(src)) add(`fonts/${f.src.split("/").pop()}`, readFileSync(src));
      const lic = src.replace(/\.[a-z0-9]+$/i, "-license.txt");
      if (existsSync(lic)) add(`fonts/${lic.split("/").pop()}`, readFileSync(lic));
    }
  }

  // The meaning behind the identity travels with it.
  const designDoc = join(dirname(opts.brandAssetsDir), "DESIGN.md");
  if (existsSync(designDoc)) add("DESIGN.md", readFileSync(designDoc));

  const manifest = {
    name: brand.name,
    version: opts.version ?? null,
    generatedAt: new Date().toISOString(),
    logos: logoVariants(brand),
    colorways: Object.keys(brand.logo.colorways),
    files: files.map((f) => f.path),
  };
  add("manifest.json", JSON.stringify(manifest, null, 2) + "\n");

  const swatches = Object.entries(brand.color).map(([k, v]) => `| ${k} | \`${typeof v === "string" ? v : v.value}\` | ${typeof v === "string" ? "foreground" : `surface, text: ${v.on}`} |`);
  add(
    "README.md",
    `# ${brand.name} brand kit

Generated by ided${opts.version ? ` from ${opts.version}` : ""}. Do not edit by hand. Change \`design/brand/brand.ts\` and re-export.
${files.some((f) => f.path === "DESIGN.md") ? "\nWhy the identity looks the way it does, and how to use it well: [DESIGN.md](DESIGN.md).\n" : ""}

## Use the tokens

- **CSS**: \`@import "tokens/tokens.css";\`, then \`var(--brand-color-ink)\`, \`var(--brand-space-m)\`, and the \`.brand-type-*\` classes.
- **Tailwind v4**: \`@import "tailwindcss"; @import "tokens/tailwind.css";\`. The default palette, spacing, radii and type scale are replaced, so only brand values compile.
- **JSON**: \`tokens/tokens.json\` (Design Tokens Community Group format) for Style Dictionary and friends.

## Colors

| token | value | role |
|---|---|---|
${swatches.join("\n")}

## Logos

| variant | colorway | vector | raster |
|---|---|---|---|
${logoRows.join("\n")}
`,
  );
  return files;
}

export function writeBrandKit(files: KitFile[], outDir: string) {
  if (existsSync(outDir)) rmSync(outDir, { recursive: true, force: true });
  for (const f of files) {
    const path = join(outDir, f.path);
    mkdirSync(dirname(path), { recursive: true });
    writeFileSync(path, f.data);
  }
}

export function zipBrandKit(files: KitFile[], folder: string): Uint8Array {
  return zipSync(Object.fromEntries(files.map((f) => [`${folder}/${f.path}`, f.data])), { level: 6 });
}
