// Brand kit: every logo variant in every colorway as SVG and PNG, plus the
// tokens as CSS, Tailwind, DTCG JSON and TypeScript. Pure Node (resvg for
// rasterizing), so it runs in CI without a browser.

import { Resvg } from "@resvg/resvg-js";
import { strToU8, zipSync } from "fflate";
import { existsSync, mkdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { factNames, formatFact } from "../shared/brand-facts.ts";
import { iconSettings, type BrandInput } from "../shared/brand-schema.ts";
import { colorwayHex, composeLogo, iconFiles, logoVariants } from "../shared/lockup.ts";
import { tailwindCss, tokensCss, tokensJson } from "../shared/tokens.ts";

export const PNG_HEIGHTS = [128, 512] as const;

export interface KitFile {
  path: string;
  data: Uint8Array;
}

export interface BuildKitOptions {
  brand: BrandInput;
  svgs: Record<string, string>;
  brandAssetsDir: string;
  version?: string;
}

function rasterize(svg: string, height: number): Uint8Array {
  const r = new Resvg(svg, { fitTo: { mode: "height", value: height }, background: "rgba(0,0,0,0)" });
  return r.render().asPng();
}

export function buildBrandKit(opts: BuildKitOptions): KitFile[] {
  const { brand, svgs } = opts;
  const files: KitFile[] = [];
  const add = (path: string, data: string | Uint8Array) => files.push({ path, data: typeof data === "string" ? strToU8(data) : data });

  const logoRows: string[] = [];
  for (const variant of logoVariants(brand)) {
    for (const colorway of Object.keys(brand.logo.colorways)) {
      const { svg } = composeLogo(brand, svgs, variant, colorwayHex(brand, colorway));
      const base = `logos/${variant}/${variant}-${colorway}`;
      add(`${base}.svg`, svg + "\n");
      for (const h of PNG_HEIGHTS) add(`${base}-${h}.png`, rasterize(svg, h));
      logoRows.push(`| ${variant} | ${colorway} | [svg](${base}.svg) | ${PNG_HEIGHTS.map((h) => `[${h}px](${base}-${h}.png)`).join(" ")} |`);
    }
  }

  // Favicons and app icons, drawn from the mark like the lockups, so no separate drawing can drift.
  const icons = iconFiles(brand, svgs);
  for (const icon of icons) add(icon.path, icon.size === null ? icon.svg + "\n" : rasterize(icon.svg, icon.size));
  const webIcons = icons.filter((i) => /icon-(192|512|maskable-512)\.png$/.test(i.path));
  add(
    "icons/manifest.json",
    JSON.stringify(
      { icons: webIcons.map((i) => ({ src: i.path.replace("icons/", ""), sizes: `${i.size}x${i.size}`, type: "image/png", ...(i.purpose ? { purpose: i.purpose } : {}) })) },
      null,
      2,
    ) + "\n",
  );

  // Fonts ship beside the tokens, and the CSS files load them.
  const fonts: string[] = [];
  for (const font of Object.values(brand.font)) {
    for (const f of font.files ?? []) {
      const src = join(opts.brandAssetsDir, f.src);
      if (existsSync(src)) {
        add(`fonts/${f.src.split("/").pop()}`, readFileSync(src));
        fonts.push(f.src);
      }
      const lic = src.replace(/\.[a-z0-9]+$/i, "-license.txt");
      if (existsSync(lic)) add(`fonts/${lic.split("/").pop()}`, readFileSync(lic));
    }
  }

  add("tokens/tokens.css", tokensCss(brand, fonts));
  add("tokens/tailwind.css", tailwindCss(brand, fonts));
  add("tokens/tokens.json", JSON.stringify(tokensJson(brand), null, 2) + "\n");
  add("tokens/brand.ts", `// ${brand.name} brand, generated by ided. Do not edit.\nexport const brand = ${JSON.stringify(brand, null, 2)} as const;\n`);

  // Facts (names, links, contact, places, handles, abbreviations), for sites and documents built
  // outside ided to read from the same source.
  if (brand.facts && factNames(brand.facts).length) add("facts.json", JSON.stringify(brand.facts, null, 2) + "\n");

  // The meaning behind the identity travels with it.
  const designDoc = join(dirname(opts.brandAssetsDir), "DESIGN.md");
  if (existsSync(designDoc)) add("DESIGN.md", readFileSync(designDoc));

  const manifest = {
    name: brand.name,
    version: opts.version ?? null,
    generatedAt: new Date().toISOString(),
    logos: logoVariants(brand),
    colorways: Object.keys(brand.logo.colorways),
    files: files.map((f) => f.path),
  };
  add("manifest.json", JSON.stringify(manifest, null, 2) + "\n");

  const swatches = Object.entries(brand.color).map(([k, v]) => `| ${k} | \`${typeof v === "string" ? v : v.value}\` | ${typeof v === "string" ? "foreground" : `surface, text: ${v.on}`} |`);
  add(
    "README.md",
    `# ${brand.name} brand kit

Generated by ided${opts.version ? ` from ${opts.version}` : ""}. Do not edit by hand. Change \`design/brand/brand.ts\` and re-export.
${files.some((f) => f.path === "DESIGN.md") ? "\nWhy the identity looks the way it does, and how to use it well: [DESIGN.md](DESIGN.md).\n" : ""}

## Use the tokens

Keep \`tokens/\` and \`fonts/\` side by side: the CSS files load the brand fonts from \`../fonts/\`.

- **CSS**: \`@import "tokens/tokens.css";\`, then \`var(--brand-color-ink)\`, \`var(--brand-space-m)\`, and the \`.brand-type-*\` classes.
- **Tailwind v4**: \`@import "tailwindcss"; @import "tokens/tailwind.css";\`. The default colors, spacing, radii, shadows, fonts and type scale are replaced by the brand's, so \`bg-blue-500\`, \`p-4\` or \`font-bold\` don't compile; each type style (\`text-body\`) carries its weight, tracking and leading. Size tokens give widths and heights (\`w-*\`, \`h-*\`, \`size-*\`, \`min-*\`, \`max-*\`) and stroke tokens border and outline widths (\`border-*\`, \`outline-*\`). Tailwind always compiles arbitrary values (\`p-[23px]\`) and bare numbers (\`border-2\`); no theme can turn those off, so keep them out in review or with a lint rule.
- **JSON**: \`tokens/tokens.json\`, in the Design Tokens Community Group format (2025.10), for Style Dictionary and other token tools.

${
    factNames(brand.facts).length
      ? `## Facts

Names, links, contact details, places and abbreviations, in \`facts.json\`. Read them from there
rather than retyping them, so a change reaches everything.

| fact | value |
|---|---|
${factNames(brand.facts)
  .map((f) => `| ${f} | ${(formatFact(brand.facts, f, "full") ?? "").replace(/\|/g, "\\|")} |`)
  .join("\n")}

`
      : ""
  }## Icons

Favicons and app icons in \`icons/\`, the mark on ${iconSettings(brand).ground}, drawn from the
same mark as every lockup. Use these rather than drawing icons by hand: change the mark (or
\`logo.icon\` in brand.ts) and re-export.

\`\`\`html
<link rel="icon" href="/icons/favicon.svg" type="image/svg+xml">
<link rel="icon" href="/icons/favicon-32.png" sizes="32x32" type="image/png">
<link rel="apple-touch-icon" href="/icons/apple-touch-icon.png">
<link rel="manifest" href="/site.webmanifest">  <!-- with the "icons" from icons/manifest.json -->
\`\`\`

\`app-icon-1024.png\` is the App Store size; \`icon-maskable-512.png\` keeps the mark inside the
circle Android may crop it to.

## Colors

| token | value | role |
|---|---|---|
${swatches.join("\n")}

## Logos

| variant | colorway | vector | raster |
|---|---|---|---|
${logoRows.join("\n")}
`,
  );
  return files;
}

export function writeBrandKit(files: KitFile[], outDir: string) {
  if (existsSync(outDir)) rmSync(outDir, { recursive: true, force: true });
  for (const f of files) {
    const path = join(outDir, f.path);
    mkdirSync(dirname(path), { recursive: true });
    writeFileSync(path, f.data);
  }
}

export function zipBrandKit(files: KitFile[], folder: string): Uint8Array {
  return zipSync(Object.fromEntries(files.map((f) => [`${folder}/${f.path}`, f.data])), { level: 6 });
}
