// Brand → CSS custom properties and portable token files. The runtime renders
// with these variables, and the brand kit ships the same names, so a deployed
// website and a design artifact read literally the same tokens.

import type { BrandInput } from "./brand-schema.ts";
import { colorValue, fontStack, typeMetrics } from "./brand-schema.ts";

export const cssVar = {
  color: (t: string) => `--brand-color-${t}`,
  space: (t: string) => `--brand-space-${t}`,
  radius: (t: string) => `--brand-radius-${t}`,
  stroke: (t: string) => `--brand-stroke-${t}`,
  size: (t: string) => `--brand-size-${t}`,
  shadow: (t: string) => `--brand-shadow-${t}`,
  font: (t: string) => `--brand-font-${t}`,
};

export function brandVariables(brand: BrandInput): Record<string, string> {
  const vars: Record<string, string> = {};
  for (const k of Object.keys(brand.color)) vars[cssVar.color(k)] = colorValue(brand, k)!;
  for (const [k, v] of Object.entries(brand.space)) vars[cssVar.space(k)] = `${v}px`;
  for (const [k, v] of Object.entries(brand.radius)) vars[cssVar.radius(k)] = `${v}px`;
  for (const [k, v] of Object.entries(brand.stroke)) vars[cssVar.stroke(k)] = `${v}px`;
  for (const [k, v] of Object.entries(brand.size ?? {})) vars[cssVar.size(k)] = `${v}px`;
  for (const [k, v] of Object.entries(brand.shadow ?? {})) vars[cssVar.shadow(k)] = v;
  for (const k of Object.keys(brand.font)) vars[cssVar.font(k)] = fontStack(brand, k);
  for (const k of Object.keys(brand.type)) {
    const m = typeMetrics(brand, k)!;
    vars[`--brand-type-${k}-size`] = `${m.size}px`;
    vars[`--brand-type-${k}-line-height`] = `${m.lineHeight}px`;
    vars[`--brand-type-${k}-weight`] = String(m.weight);
    vars[`--brand-type-${k}-tracking`] = `${m.tracking}em`;
  }
  return vars;
}

export function fontFaceCss(brand: BrandInput, assetUrl: (path: string) => string): string {
  const rules: string[] = [];
  for (const f of Object.values(brand.font)) {
    for (const file of f.files ?? []) {
      rules.push(
        `@font-face{font-family:"${f.family}";src:url("${assetUrl(file.src)}");font-weight:${file.weight};font-style:${file.style ?? "normal"};font-display:block;}`,
      );
    }
  }
  return rules.join("\n");
}

export function tokensCss(brand: BrandInput): string {
  const vars = brandVariables(brand);
  const lines = Object.entries(vars).map(([k, v]) => `  ${k}: ${v};`);
  const typeClasses = Object.keys(brand.type).map((k) => {
    const t = brand.type[k]!;
    return [
      `.brand-type-${k} {`,
      `  font-family: var(${cssVar.font(t.font)});`,
      `  font-size: var(--brand-type-${k}-size);`,
      `  line-height: var(--brand-type-${k}-line-height);`,
      `  font-weight: var(--brand-type-${k}-weight);`,
      `  letter-spacing: var(--brand-type-${k}-tracking);`,
      t.case === "upper" ? "  text-transform: uppercase;" : null,
      `}`,
    ]
      .filter(Boolean)
      .join("\n");
  });
  return `/* ${brand.name} design tokens. Generated by ided; do not edit. */\n:root {\n${lines.join("\n")}\n}\n\n${typeClasses.join("\n\n")}\n`;
}

/**
 * Tailwind v4 theme that *replaces* the default scales, so `bg-blue-500` or
 * `rounded-xl` simply do not exist in a brand-locked codebase.
 */
export function tailwindCss(brand: BrandInput): string {
  const out: string[] = [`/* ${brand.name} Tailwind v4 theme. Generated by ided; do not edit. */`, "@theme {"];
  out.push("  --color-*: initial;");
  for (const k of Object.keys(brand.color)) out.push(`  --color-${k}: ${colorValue(brand, k)};`);
  out.push("  --spacing-*: initial;");
  for (const [k, v] of Object.entries(brand.space)) out.push(`  --spacing-${k}: ${v}px;`);
  out.push("  --radius-*: initial;");
  for (const [k, v] of Object.entries(brand.radius)) out.push(`  --radius-${k}: ${v}px;`);
  out.push("  --font-*: initial;");
  for (const k of Object.keys(brand.font)) out.push(`  --font-${k}: ${fontStack(brand, k)};`);
  out.push("  --text-*: initial;");
  for (const k of Object.keys(brand.type)) {
    const m = typeMetrics(brand, k)!;
    out.push(`  --text-${k}: ${m.size}px;`);
    out.push(`  --text-${k}--line-height: ${m.lineHeight}px;`);
    out.push(`  --text-${k}--letter-spacing: ${m.tracking}em;`);
    out.push(`  --text-${k}--font-weight: ${m.weight};`);
  }
  if (brand.shadow) {
    out.push("  --shadow-*: initial;");
    for (const [k, v] of Object.entries(brand.shadow)) out.push(`  --shadow-${k}: ${v};`);
  }
  out.push("}");
  return out.join("\n") + "\n";
}

/** Design Tokens Community Group format. */
export function tokensJson(brand: BrandInput): unknown {
  const group = <T>(obj: Record<string, T> | undefined, type: string, value: (v: T, k: string) => unknown) =>
    Object.fromEntries(Object.entries(obj ?? {}).map(([k, v]) => [k, { $type: type, $value: value(v, k) }]));
  return {
    $description: `${brand.name} design tokens, generated by ided.`,
    color: group(brand.color, "color", (_v, k) => colorValue(brand, k)),
    space: group(brand.space, "dimension", (v) => `${v}px`),
    radius: group(brand.radius, "dimension", (v) => `${v}px`),
    stroke: group(brand.stroke, "dimension", (v) => `${v}px`),
    size: group(brand.size, "dimension", (v) => `${v}px`),
    shadow: group(brand.shadow, "shadow", (v) => v),
    font: group(brand.font, "fontFamily", (_v, k) => fontStack(brand, k)),
    typography: Object.fromEntries(
      Object.keys(brand.type).map((k) => {
        const m = typeMetrics(brand, k)!;
        return [
          k,
          {
            $type: "typography",
            $value: {
              fontFamily: m.family,
              fontSize: `${m.size}px`,
              fontWeight: m.weight,
              lineHeight: `${m.lineHeight}px`,
              letterSpacing: `${m.tracking}em`,
              textTransform: m.upper ? "uppercase" : "none",
            },
          },
        ];
      }),
    ),
  };
}
