// Brand → CSS custom properties and portable token files. The runtime renders
// with these variables, and the brand kit ships the same names, so a deployed
// website and a design artifact read literally the same tokens.

import type { BrandInput } from "./brand-schema.ts";
import { colorValue, fontStack, typeMetrics } from "./brand-schema.ts";
import { parseShadow, readColor, toHex } from "./color.ts";

export const cssVar = {
  color: (t: string) => `--brand-color-${t}`,
  space: (t: string) => `--brand-space-${t}`,
  radius: (t: string) => `--brand-radius-${t}`,
  stroke: (t: string) => `--brand-stroke-${t}`,
  size: (t: string) => `--brand-size-${t}`,
  shadow: (t: string) => `--brand-shadow-${t}`,
  font: (t: string) => `--brand-font-${t}`,
};

export function brandVariables(brand: BrandInput): Record<string, string> {
  const vars: Record<string, string> = {};
  for (const k of Object.keys(brand.color)) vars[cssVar.color(k)] = colorValue(brand, k)!;
  for (const [k, v] of Object.entries(brand.space)) vars[cssVar.space(k)] = `${v}px`;
  for (const [k, v] of Object.entries(brand.radius)) vars[cssVar.radius(k)] = `${v}px`;
  for (const [k, v] of Object.entries(brand.stroke)) vars[cssVar.stroke(k)] = `${v}px`;
  for (const [k, v] of Object.entries(brand.size ?? {})) vars[cssVar.size(k)] = `${v}px`;
  for (const [k, v] of Object.entries(brand.shadow ?? {})) vars[cssVar.shadow(k)] = v;
  for (const k of Object.keys(brand.font)) vars[cssVar.font(k)] = fontStack(brand, k);
  for (const k of Object.keys(brand.type)) {
    const m = typeMetrics(brand, k)!;
    vars[`--brand-type-${k}-size`] = `${m.size}px`;
    vars[`--brand-type-${k}-line-height`] = `${m.lineHeight}px`;
    vars[`--brand-type-${k}-weight`] = String(m.weight);
    vars[`--brand-type-${k}-tracking`] = `${m.tracking}em`;
  }
  return vars;
}

/**
 * `@font-face` rules for the brand's font files. `assetUrl` gives a file's URL, or null to leave it
 * out. Renders wait for the font (`block`); a website shows its fallback first (`swap`).
 */
export function fontFaceCss(brand: BrandInput, assetUrl: (path: string) => string | null, display: "block" | "swap" = "block"): string {
  const rules: string[] = [];
  for (const f of Object.values(brand.font)) {
    for (const file of f.files ?? []) {
      const url = assetUrl(file.src);
      if (url === null) continue;
      rules.push(
        `@font-face{font-family:"${f.family}";src:url("${url}");font-weight:${file.weight};font-style:${file.style ?? "normal"};font-display:${display};}`,
      );
    }
  }
  return rules.join("\n");
}

/** Font faces for the brand kit's CSS files, which sit in `tokens/` beside `fonts/`. */
function kitFontFaces(brand: BrandInput, fonts: readonly string[]): string {
  const css = fontFaceCss(brand, (src) => (fonts.includes(src) ? `../fonts/${src.split("/").pop()}` : null), "swap");
  return css ? `${css}\n\n` : "";
}

/** `fonts`: the font files (as brand.ts names them) that ship beside the tokens. */
export function tokensCss(brand: BrandInput, fonts: readonly string[] = []): string {
  const vars = brandVariables(brand);
  const lines = Object.entries(vars).map(([k, v]) => `  ${k}: ${v};`);
  const typeClasses = Object.keys(brand.type).map((k) => {
    const t = brand.type[k]!;
    return [
      `.brand-type-${k} {`,
      `  font-family: var(${cssVar.font(t.font)});`,
      `  font-size: var(--brand-type-${k}-size);`,
      `  line-height: var(--brand-type-${k}-line-height);`,
      `  font-weight: var(--brand-type-${k}-weight);`,
      `  letter-spacing: var(--brand-type-${k}-tracking);`,
      t.case === "upper" ? "  text-transform: uppercase;" : null,
      `}`,
    ]
      .filter(Boolean)
      .join("\n");
  });
  return `/* ${brand.name} design tokens. Generated by ided; do not edit. */\n${kitFontFaces(brand, fonts)}:root {\n${lines.join("\n")}\n}\n\n${typeClasses.join("\n\n")}\n`;
}

/**
 * Tailwind v4 theme that *replaces* the default scales, so `bg-blue-500`, `p-4`, `shadow-md` or
 * `font-bold` simply do not exist in a brand-locked codebase. Weight, tracking and leading come
 * with each type style (`text-body`). Size tokens become widths and heights (`w-icon`,
 * `size-avatar`, `max-w-measure`) and stroke tokens border and outline widths (`border-hairline`).
 * What no theme can remove: arbitrary values (`p-[23px]`) and bare numbers (`border-2`).
 */
export function tailwindCss(brand: BrandInput, fonts: readonly string[] = []): string {
  const out: string[] = [`/* ${brand.name} Tailwind v4 theme. Generated by ided; do not edit. */`];
  const faces = kitFontFaces(brand, fonts);
  if (faces) out.push(faces.trimEnd(), "");
  out.push("@theme {");
  out.push("  --color-*: initial;");
  for (const k of Object.keys(brand.color)) out.push(`  --color-${k}: ${colorValue(brand, k)};`);
  out.push("  --spacing-*: initial;");
  for (const [k, v] of Object.entries(brand.space)) out.push(`  --spacing-${k}: ${v}px;`);
  out.push("  --radius-*: initial;");
  for (const [k, v] of Object.entries(brand.radius)) out.push(`  --radius-${k}: ${v}px;`);
  out.push("  --font-*: initial;");
  for (const k of Object.keys(brand.font)) out.push(`  --font-${k}: ${fontStack(brand, k)};`);
  out.push("  --text-*: initial;");
  for (const k of Object.keys(brand.type)) {
    const m = typeMetrics(brand, k)!;
    out.push(`  --text-${k}: ${m.size}px;`);
    out.push(`  --text-${k}--line-height: ${m.lineHeight}px;`);
    out.push(`  --text-${k}--letter-spacing: ${m.tracking}em;`);
    out.push(`  --text-${k}--font-weight: ${m.weight};`);
  }
  out.push("  --font-weight-*: initial;", "  --tracking-*: initial;", "  --leading-*: initial;", "  --container-*: initial;");
  out.push("  --shadow-*: initial;", "  --inset-shadow-*: initial;", "  --drop-shadow-*: initial;");
  for (const [k, v] of Object.entries(brand.shadow ?? {})) out.push(`  --shadow-${k}: ${v};`);
  for (const [k, v] of Object.entries(brand.size ?? {})) out.push(`  --size-${k}: ${v}px;`);
  for (const [k, v] of Object.entries(brand.stroke)) out.push(`  --stroke-${k}: ${v}px;`);
  out.push("}");
  const utility = (name: string, decls: string[], ns: string) => `@utility ${name}-* {\n${decls.map((d) => `  ${d}: --value(--${ns}-*);`).join("\n")}\n}`;
  if (brand.size && Object.keys(brand.size).length) {
    out.push("");
    for (const [name, decls] of [
      ["w", ["width"]],
      ["h", ["height"]],
      ["size", ["width", "height"]],
      ["min-w", ["min-width"]],
      ["max-w", ["max-width"]],
      ["min-h", ["min-height"]],
      ["max-h", ["max-height"]],
    ] as const)
      out.push(utility(name, [...decls], "size"));
  }
  out.push("");
  for (const [name, decl] of [
    ["border", "border-width"],
    ["border-x", "border-inline-width"],
    ["border-y", "border-block-width"],
    ["border-t", "border-top-width"],
    ["border-r", "border-right-width"],
    ["border-b", "border-bottom-width"],
    ["border-l", "border-left-width"],
    ["outline", "outline-width"],
  ] as const)
    out.push(utility(name, [decl], "stroke"));
  return out.join("\n") + "\n";
}

/** A DTCG color: sRGB components from 0 to 1, with the hex as a fallback. */
function dtcgColor(raw: string): unknown {
  const c = readColor(raw);
  if (!c) throw new Error(`Not a color: ${raw}`);
  const unit = (n: number) => Number((n / 255).toFixed(4));
  return { colorSpace: "srgb", components: [unit(c.r), unit(c.g), unit(c.b)], ...(c.a < 1 ? { alpha: Number(c.a.toFixed(4)) } : {}), hex: toHex(c) };
}

const px = (value: number) => ({ value: Number(value.toFixed(4)), unit: "px" });

/** A font stack as the list of family names DTCG expects. */
function families(stack: string): string[] {
  return stack.split(",").map((f) => f.trim().replace(/^["']|["']$/g, "")).filter(Boolean);
}

/** Design Tokens Community Group format (2025.10). */
export function tokensJson(brand: BrandInput): unknown {
  const group = <T>(obj: Record<string, T> | undefined, type: string, value: (v: T, k: string) => unknown) =>
    Object.fromEntries(Object.entries(obj ?? {}).map(([k, v]) => [k, { $type: type, $value: value(v, k) }]));
  return {
    $description: `${brand.name} design tokens, generated by ided.`,
    color: group(brand.color, "color", (_v, k) => dtcgColor(colorValue(brand, k)!)),
    space: group(brand.space, "dimension", (v) => px(v)),
    radius: group(brand.radius, "dimension", (v) => px(v)),
    stroke: group(brand.stroke, "dimension", (v) => px(v)),
    size: group(brand.size, "dimension", (v) => px(v)),
    shadow: group(brand.shadow, "shadow", (v) => {
      const layers = parseShadow(v)!.map((l) => ({ color: dtcgColor(l.color), offsetX: px(l.offsetX), offsetY: px(l.offsetY), blur: px(l.blur), spread: px(l.spread), ...(l.inset ? { inset: true } : {}) }));
      return layers.length === 1 ? layers[0] : layers;
    }),
    font: group(brand.font, "fontFamily", (_v, k) => families(fontStack(brand, k))),
    typography: Object.fromEntries(
      Object.keys(brand.type).map((k) => {
        const m = typeMetrics(brand, k)!;
        return [
          k,
          {
            $type: "typography",
            $value: {
              fontFamily: families(m.family),
              fontSize: px(m.size),
              fontWeight: m.weight,
              letterSpacing: px(m.tracking * m.size),
              lineHeight: Number((m.lineHeight / m.size).toFixed(4)),
            },
            ...(m.upper ? { $extensions: { "dev.ided": { textTransform: "uppercase" } } } : {}),
          },
        ];
      }),
    ),
  };
}
