// Scaffolding: the only sanctioned way to create workspaces, projects and
// frames, so every file starts in the canonical shape.

import { copyFileSync, existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join, relative } from "node:path";
import {
  isFrameKind,
  FRAME_DIR,
  FRAME_NOUN,
  FRAME_ROOT,
  PROJECT_DIR_RE,
  type FrameKind,
  type ProjectManifest,
} from "../shared/formats.ts";
import { dependencyDir, DESIGN_DIR, GENERATED_DIR, TYPES_DIR, WORKSPACE_MARKER } from "./paths.ts";
import { markSvg, wordmarkSvg } from "./wordmark.ts";
import { getProject, scanWorkspace, type Workspace } from "./workspace.ts";

function write(file: string, content: string, overwrite = false) {
  if (!overwrite && existsSync(file)) return false;
  mkdirSync(dirname(file), { recursive: true });
  writeFileSync(file, content);
  return true;
}

export function pascal(slug: string): string {
  const s = slug.replace(/(^|-)([a-z0-9])/g, (_, __, c: string) => c.toUpperCase());
  return /^[0-9]/.test(s) ? `Frame${s}` : s;
}

export function titleCase(slug: string): string {
  return slug.replace(/-/g, " ").replace(/\b\w/g, (c) => c.toUpperCase());
}

export function slugify(input: string): string {
  return input
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
}

// ---------------------------------------------------------------------------
// Generated support files (design/.ided): types and editor config.
// ---------------------------------------------------------------------------

/** Write only when content changed: Vite reloads the page when a tsconfig is touched. */
function writeIfChanged(file: string, content: string) {
  if (existsSync(file) && readFileSync(file, "utf8") === content) return;
  writeFileSync(file, content);
}

export function writeGenerated(root: string) {
  const gen = join(root, DESIGN_DIR, GENERATED_DIR);
  const ws = scanWorkspace(root);
  mkdirSync(gen, { recursive: true });
  const types = (p: string) => join(TYPES_DIR, p);
  const tsconfig = {
    compilerOptions: {
      target: "ES2022",
      module: "ESNext",
      moduleResolution: "bundler",
      lib: ["ES2022", "DOM"],
      jsx: "react-jsx",
      jsxImportSource: "ided",
      strict: true,
      noEmit: true,
      skipLibCheck: true,
      isolatedModules: true,
      allowImportingTsExtensions: true,
      noUnusedLocals: true,
      noUnusedParameters: true,
      noFallthroughCasesInSwitch: true,
      types: [],
      paths: {
        ided: [types("runtime/index.d.ts")],
        "ided/jsx-runtime": [types("runtime/jsx-runtime.d.ts")],
        "ided/jsx-dev-runtime": [types("runtime/jsx-dev-runtime.d.ts")],
        // One mapping for every package, so adding a project does not change this file:
        // Vite reloads every open page, exports included, when a tsconfig changes.
        "@*": ["../*"],
      },
    },
    include: ["../**/*.ts", "../**/*.tsx", "./register.d.ts", "./assets.d.ts"],
    exclude: ["./cache"],
  };
  writeIfChanged(join(gen, "tsconfig.json"), JSON.stringify(tsconfig, null, 2) + "\n");
  writeIfChanged(
    join(gen, "register.d.ts"),
    `// Generated by ided. Registers this workspace's brand so token props are typed.\nimport type brand from "../brand/brand";\ndeclare module "ided" {\n  interface Register {\n    brand: typeof brand;\n  }\n}\nexport {};\n`,
  );
  // One exact module per asset file: importing a file that does not exist is a type error.
  const assetDecls = ws.projects.flatMap((p) =>
    p.assets
      .filter((a) => !a.startsWith("fonts/"))
      .map((a) => `declare module "@${p.id}/assets/${a}" {\n  const asset: import("ided").ImageAsset;\n  export default asset;\n}`),
  );
  writeIfChanged(join(gen, "assets.d.ts"), `// Generated by ided from every package's assets/. Do not edit.\n${assetDecls.join("\n")}\n`);
  writeIfChanged(join(gen, "README.md"), "Generated by ided on every `ided run` / `ided check`. Do not edit or commit.\n");
  write(join(root, DESIGN_DIR, "tsconfig.json"), `{\n  "extends": "./.ided/tsconfig.json"\n}\n`);
}

// ---------------------------------------------------------------------------
// Workspace
// ---------------------------------------------------------------------------

export function brandTemplate(name: string): string {
  return `import { defineBrand } from "ided";

// The single source of every value in this workspace. Artifacts reference
// these tokens by name; they never contain a color, length or font of their own.
export default defineBrand({
  name: ${JSON.stringify(name)},

  // Base grid in px. Every space, radius, size and line height is a multiple of it.
  unit: 4,

  // Surfaces ({ value, on }) can be backgrounds and declare their own text and
  // logo colors. Plain hex colors are foreground-only.
  color: {
    paper: { value: "#FAFAF7", on: "ink", logo: "primary" },
    sand: { value: "#EDEAE2", on: "ink", logo: "black" },
    ink: { value: "#111113", on: "paper", logo: "reversed" },
    accent: { value: "#FF4F1F", on: "ink", logo: "black" },
    muted: "#62626A",
    line: "#D9D6CE",
  },

  space: {
    "2xs": 4,
    xs: 8,
    s: 12,
    m: 16,
    l: 24,
    xl: 32,
    "2xl": 48,
    "3xl": 64,
    "4xl": 96,
    "5xl": 128,
    "6xl": 192,
  },

  radius: { s: 8, m: 16, l: 32, xl: 48 },
  stroke: { hairline: 1, thin: 2, thick: 4 },
  size: { icon: 32, avatar: 96, thumb: 320, measure: 1200 },
  shadow: {
    raised: "0 1px 2px rgba(17, 17, 19, 0.06), 0 12px 32px rgba(17, 17, 19, 0.10)",
  },

  font: {
    sans: {
      family: "Inter",
      fallback: '-apple-system, "Helvetica Neue", Helvetica, Arial, sans-serif',
      files: [{ src: "fonts/inter.woff2", weight: "100 900" }],
    },
    mono: {
      family: "JetBrains Mono",
      fallback: 'ui-monospace, "SF Mono", Menlo, monospace',
      files: [{ src: "fonts/jetbrains-mono.woff2", weight: "100 800" }],
    },
  },

  // One type scale for every medium. Doc pages render at 2x, so body copy
  // reads the same on a slide and prints at 10.5pt.
  type: {
    display: { font: "sans", size: 160, weight: 700, leading: 0.95, tracking: -0.045, wrap: "balance" },
    title: { font: "sans", size: 96, weight: 700, leading: 1, tracking: -0.035, wrap: "balance" },
    heading: { font: "sans", size: 56, weight: 600, leading: 1.1, tracking: -0.02, wrap: "balance" },
    subhead: { font: "sans", size: 36, weight: 500, leading: 1.25, tracking: -0.01 },
    body: { font: "sans", size: 28, weight: 400, leading: 1.45, emphasisWeight: 600 },
    small: { font: "sans", size: 22, weight: 400, leading: 1.45, emphasisWeight: 600 },
    code: { font: "mono", size: 22, weight: 400, leading: 1.5 },
    label: { font: "sans", size: 18, weight: 600, leading: 1.3, tracking: 0.08, case: "upper" },
  },

  // Frame margins per medium.
  margin: { deck: "4xl", doc: "5xl", graphic: "3xl", web: "3xl" },

  logo: {
    mark: "mark.svg",
    wordmark: "wordmark.svg",
    // Geometry relative to the wordmark height, so lockups are scale-free.
    lockups: {
      horizontal: { direction: "row", mark: 2.2, gap: 1, align: "center" },
      stacked: { direction: "column", mark: 4, gap: 1.2, align: "center" },
    },
    colorways: {
      primary: { mark: "accent", wordmark: "ink" },
      reversed: { mark: "accent", wordmark: "paper" },
      black: { mark: "ink", wordmark: "ink" },
      white: { mark: "paper", wordmark: "paper" },
    },
    sizes: { xs: 24, s: 40, m: 64, l: 96, xl: 160 },
  },
});
`;
}

const CORNER_MARK = `import { Logo, Place } from "ided";

/**
 * The mark, pinned to the top-right corner at the frame margin. Every medium
 * uses this component, so the mark sits at the same distance from the corner
 * on a slide, a page and a social graphic.
 */
export function CornerMark() {
  return (
    <Place anchor="top-right" inset="margin">
      <Logo variant="mark" size="s" />
    </Place>
  );
}
`;

const FOOTER = `import { FrameNumber, Row, Text } from "ided";

/** Brand name and frame number along the bottom edge. */
export function Footer(props: { label: string }) {
  return (
    <Row justify="between" align="end">
      <Text type="label">{props.label}</Text>
      <Text type="label">
        <FrameNumber format="nn" />
      </Text>
    </Row>
  );
}
`;

export interface InitOptions {
  name: string;
  sample: boolean;
}

export function initWorkspace(root: string, opts: InitOptions): string[] {
  const created: string[] = [];
  const put = (rel: string, content: string) => {
    if (write(join(root, rel), content)) created.push(rel);
  };
  put(WORKSPACE_MARKER, JSON.stringify({ version: 1 }, null, 2) + "\n");
  put(`${DESIGN_DIR}/brand/project.json`, JSON.stringify({ kind: "brand", title: `${opts.name} Brand` }, null, 2) + "\n");
  put(`${DESIGN_DIR}/brand/brand.ts`, brandTemplate(opts.name));
  put(`${DESIGN_DIR}/brand/assets/mark.svg`, markSvg());
  put(`${DESIGN_DIR}/brand/assets/wordmark.svg`, wordmarkSvg(opts.name));
  put(`${DESIGN_DIR}/brand/components/corner-mark.tsx`, CORNER_MARK);
  put(`${DESIGN_DIR}/brand/components/footer.tsx`, FOOTER);
  const fonts = [
    ["@fontsource-variable/inter", "files/inter-latin-wght-normal.woff2", "inter.woff2", "inter-license.txt"],
    ["@fontsource-variable/jetbrains-mono", "files/jetbrains-mono-latin-wght-normal.woff2", "jetbrains-mono.woff2", "jetbrains-mono-license.txt"],
  ] as const;
  for (const [pkg, src, dest, licDest] of fonts) {
    const target = join(root, DESIGN_DIR, "brand/assets/fonts", dest);
    if (!existsSync(target)) {
      mkdirSync(dirname(target), { recursive: true });
      copyFileSync(join(dependencyDir(pkg), src), target);
      copyFileSync(join(dependencyDir(pkg), "LICENSE"), join(dirname(target), licDest));
      created.push(relative(root, target));
    }
  }
  const gitignore = join(root, DESIGN_DIR, ".gitignore");
  if (write(gitignore, `${GENERATED_DIR}/\n`)) created.push(relative(root, gitignore));
  writeGenerated(root);
  if (opts.sample) {
    const ws = scanWorkspace(root);
    if (!ws.projects.some((p) => p.id === "intro")) {
      created.push(...newProject(ws, "deck", "intro", { title: "Design as Code" }));
      const dir = join(root, DESIGN_DIR, "intro", "slides");
      for (const [file, body] of Object.entries(SAMPLE_SLIDES(opts.name))) {
        writeFileSync(join(dir, file), body);
      }
      created.push(...Object.keys(SAMPLE_SLIDES(opts.name)).map((f) => `${DESIGN_DIR}/intro/slides/${f}`));
    }
  }
  return [...new Set(created)];
}

// ---------------------------------------------------------------------------
// Projects and frames
// ---------------------------------------------------------------------------

export interface NewProjectOptions {
  title?: string;
  page?: "letter" | "a4";
  size?: string;
  viewport?: string;
}

export function manifestFor(kind: FrameKind, title: string, opts: NewProjectOptions): ProjectManifest {
  switch (kind) {
    case "deck":
      return { kind, title };
    case "doc":
      return { kind, title, page: opts.page ?? "letter" };
    case "graphic":
      return { kind, title, size: (opts.size ?? "square") as never };
    case "web":
      return { kind, title, viewport: (opts.viewport ?? "desktop") as never };
  }
}

/** A new library: project.json plus one example component. */
function newLibrary(ws: Workspace, id: string, title: string): string[] {
  const dir = join(ws.designDir, id);
  write(join(dir, "project.json"), JSON.stringify({ kind: "library", title }, null, 2) + "\n");
  const comp = join(dir, "components", "card.tsx");
  write(comp, componentTemplate("card"));
  return [relative(ws.root, join(dir, "project.json")), relative(ws.root, comp)];
}

export function componentTemplate(slug: string): string {
  const fn = pascal(slug);
  return `import { Box, Stack, Text, type SurfaceToken } from "ided";

/** Describe when to use ${fn}. Props take tokens, never raw values. */
export function ${fn}(props: { title: string; body: string; surface?: SurfaceToken }) {
  return (
    <Box surface={props.surface ?? "paper"} pad="2xl" radius="l">
      <Stack gap="m">
        <Text type="subhead">{props.title}</Text>
        <Text type="body" color="muted">
          {props.body}
        </Text>
      </Stack>
    </Box>
  );
}
`;
}

export function newProject(ws: Workspace, kind: FrameKind | "library", id: string, opts: NewProjectOptions = {}): string[] {
  if (!PROJECT_DIR_RE.test(id)) throw new Error(`Project names are lowercase kebab-case ("${id}" is not). Try "${slugify(id)}".`);
  if (id === "brand") throw new Error('"brand" is reserved for the brand project.');
  const dir = join(ws.designDir, id);
  if (existsSync(dir)) throw new Error(`design/${id} already exists.`);
  const title = opts.title ?? titleCase(id);
  if (kind === "library") return newLibrary(ws, id, title);
  const manifest = manifestFor(kind, title, opts);
  const rel = (p: string) => relative(ws.root, p);
  write(join(dir, "project.json"), JSON.stringify(manifest, null, 2) + "\n");
  const first = join(dir, FRAME_DIR[kind], `01-${kind === "deck" ? "title" : kind === "doc" ? "cover" : kind === "web" ? "home" : "main"}.tsx`);
  write(first, frameTemplate(kind, first.split("/").pop()!.replace(/^\d+-|\.tsx$/g, ""), title));
  return [rel(join(dir, "project.json")), rel(first)];
}

export function frameTemplate(kind: FrameKind, slug: string, heading = titleCase(slug)): string {
  const root = FRAME_ROOT[kind];
  const fn = pascal(slug);
  const text = JSON.stringify(heading).slice(1, -1);
  if (kind === "web") {
    return `import { Row, Screen, Stack, Text, Logo } from "ided";

export default function ${fn}() {
  return (
    <${root} surface="paper" gap="4xl">
      <Row justify="between" align="center">
        <Logo variant="horizontal" size="xs" />
        <Row gap="xl">
          <Text type="small">Product</Text>
          <Text type="small">Pricing</Text>
          <Text type="small">About</Text>
        </Row>
      </Row>
      <Stack gap="l" width="2/3">
        <Text type="display">${text}</Text>
        <Text type="subhead" color="muted">
          One sentence that says what this is for.
        </Text>
      </Stack>
    </${root}>
  );
}
`;
  }
  return `import { ${root}, Stack, Text } from "ided";
import { CornerMark } from "@brand/components/corner-mark";

export default function ${fn}() {
  return (
    <${root} surface="paper" justify="end">
      <CornerMark />
      <Stack gap="l">
        <Text type="title">${text}</Text>
        <Text type="subhead" color="muted">
          Replace with a one-line summary.
        </Text>
      </Stack>
    </${root}>
  );
}
`;
}

export interface AddFrameResult {
  file: string;
}

/**
 * Add the next numbered frame to a frame project, or a component to a library
 * or the brand. Never renumbers existing frames.
 */
export function addFrame(ws: Workspace, projectId: string, name: string): AddFrameResult {
  const p = getProject(ws, projectId);
  if (!p.manifest) throw new Error(`"${projectId}" has an invalid project.json; run \`ided check\`.`);
  const slug = slugify(name);
  if (!slug) throw new Error("Name must contain letters or digits.");
  if (!isFrameKind(p.kind)) {
    const abs = join(p.dir, "components", `${slug}.tsx`);
    if (existsSync(abs)) throw new Error(`${relative(ws.root, abs)} already exists.`);
    write(abs, componentTemplate(slug));
    return { file: relative(ws.root, abs) };
  }
  const kind = p.kind;
  const next = (p.frames.at(-1)?.number ?? 0) + 1;
  const width = Math.max(2, String(next).length);
  const fileName = `${String(next).padStart(width, "0")}-${slug}.tsx`;
  const abs = join(p.dir, FRAME_DIR[kind], fileName);
  write(abs, frameTemplate(kind, slug));
  return { file: relative(ws.root, abs) };
}

/** Declare that `projectId` imports from `library`. */
export function useLibrary(ws: Workspace, projectId: string, library: string): string {
  const p = getProject(ws, projectId);
  const lib = getProject(ws, library);
  if (lib.kind !== "library") throw new Error(`"${library}" is a ${lib.kind}; only libraries can be dependencies.`);
  if (p.kind === "brand") throw new Error("The brand cannot depend on anything; libraries depend on the brand.");
  if (p.id === lib.id) throw new Error("A project cannot depend on itself.");
  const file = join(p.dir, "project.json");
  const original = readFileSync(file, "utf8");
  const manifest = JSON.parse(original) as { dependencies?: string[] };
  const deps = new Set(manifest.dependencies ?? []);
  if (deps.has(library)) return `${projectId} already uses ${library}`;
  deps.add(library);
  manifest.dependencies = [...deps].sort();
  writeFileSync(file, JSON.stringify(manifest, null, 2) + "\n");
  const cycle = scanWorkspace(ws.root)
    .projects.flatMap((x) => x.issues)
    .find((i) => i.message.startsWith("Dependency cycle") && i.message.includes(projectId) && i.message.includes(library));
  if (cycle) {
    writeFileSync(file, original);
    throw new Error(`Not added: ${cycle.message}`);
  }
  return `${projectId} now uses ${library}: import from "@${library}/components/<name>" and "@${library}/assets/<file>"`;
}

export function describeKinds(): string {
  return (Object.keys(FRAME_DIR) as FrameKind[]).map((k) => `${k} (${FRAME_NOUN[k]}s in ${FRAME_DIR[k]}/, root <${FRAME_ROOT[k]}>)`).join(", ");
}

// ---------------------------------------------------------------------------
// Sample deck
// ---------------------------------------------------------------------------

const SAMPLE_SLIDES = (brand: string): Record<string, string> => ({
  "01-title.tsx": `import { Slide, Stack, Text, Logo } from "ided";
import { Footer } from "@brand/components/footer";

export default function Title() {
  return (
    <Slide surface="ink" justify="between">
      <Logo variant="horizontal" size="m" />
      <Stack gap="xl" width="3/4">
        <Text type="display">Design as code.</Text>
        <Text type="subhead">
          Every value comes from the brand. Every layout is a function. Nothing is eyeballed.
        </Text>
      </Stack>
      <Footer label=${JSON.stringify(brand)} />
    </Slide>
  );
}
`,
  "02-principles.tsx": `import { Slide, Stack, Row, Text, Em, Divider, List } from "ided";
import { CornerMark } from "@brand/components/corner-mark";
import { Footer } from "@brand/components/footer";

export default function Principles() {
  return (
    <Slide surface="paper" justify="between">
      <CornerMark />
      <Text type="label" color="muted">
        Principles
      </Text>
      <Row gap="4xl" align="start">
        <Stack gap="l" width="1/2">
          <Text type="title">
            One way to <Em color="accent">do everything.</Em>
          </Text>
        </Stack>
        <Divider color="line" weight="hairline" />
        <Stack gap="xl" grow>
          <List
            type="subhead"
            gap="l"
            marker="number"
            items={[
              "Values are tokens, never literals.",
              "Layout is Stack, Row, Grid and Place.",
              "Text is a type style, never a font size.",
              "Nested corners are concentric by construction.",
            ]}
          />
        </Stack>
      </Row>
      <Footer label=${JSON.stringify(brand)} />
    </Slide>
  );
}
`,
  "03-numbers.tsx": `import { Slide, Grid, Box, Stack, Text } from "ided";
import { CornerMark } from "@brand/components/corner-mark";
import { Footer } from "@brand/components/footer";

const stats = [
  { value: "0", label: "raw pixel values in this deck" },
  { value: "16", label: "primitives in the whole vocabulary" },
  { value: "1", label: "brand file every medium reads from" },
];

export default function Numbers() {
  return (
    <Slide surface="sand" justify="between">
      <CornerMark />
      <Text type="heading">Constraints you can count.</Text>
      <Grid columns={3} gap="l">
        {stats.map((s) => (
          <Box key={s.label} surface="paper" pad="2xl" radius="l">
            <Stack gap="m">
              <Text type="display">{s.value}</Text>
              <Text type="body" color="muted">
                {s.label}
              </Text>
            </Stack>
          </Box>
        ))}
      </Grid>
      <Footer label=${JSON.stringify(brand)} />
    </Slide>
  );
}
`,
  "04-concentric.tsx": `import { Slide, Row, Box, Stack, Text } from "ided";
import { CornerMark } from "@brand/components/corner-mark";
import { Footer } from "@brand/components/footer";

export default function Concentric() {
  return (
    <Slide surface="paper" justify="between">
      <CornerMark />
      <Row gap="4xl" align="center" grow>
        <Stack gap="l" width="1/2">
          <Text type="heading">Corners that line up.</Text>
          <Text type="body" color="muted">
            An inner radius is the outer radius minus the padding between them. Write radius="concentric" and the
            framework does the arithmetic, at any size.
          </Text>
        </Stack>
        <Box surface="ink" pad="l" radius="xl" grow>
          <Box surface="accent" pad="m" radius="concentric" ratio="16:9">
            <Box surface="paper" pad="l" radius="concentric" grow>
              <Text type="label">radius = concentric</Text>
            </Box>
          </Box>
        </Box>
      </Row>
      <Footer label=${JSON.stringify(brand)} />
    </Slide>
  );
}
`,
});

export function readJson<T>(file: string, fallback: T): T {
  try {
    return JSON.parse(readFileSync(file, "utf8")) as T;
  } catch {
    return fallback;
  }
}
