#!/usr/bin/env node
// Renders the Homebrew formula for a release. The release workflow runs this
// with the published tarball's URL and checksum and commits the result to the
// tap repository (<owner>/homebrew-tap, as Formula/ide-design.rb). The command it installs
// is `ided`, the short name.
//
//   node packaging/homebrew/formula.mjs --version 0.1.0 --url <tarball> --sha256 <hex> --homepage <url>

import { parseArgs } from "node:util";

export function formula({ version, url, sha256, homepage }) {
  for (const [k, v] of Object.entries({ version, url, sha256, homepage })) {
    if (!v) throw new Error(`missing --${k}`);
  }
  if (!/^[0-9a-f]{64}$/.test(sha256)) throw new Error("--sha256 must be 64 hex characters");
  return `# Generated by packaging/homebrew/formula.mjs in the ide-design repository. Do not edit here.
class IdeDesign < Formula
  desc "Parametric graphic design: token-only React artifacts checked like code"
  homepage "${homepage}"
  url "${url}"
  sha256 "${sha256}"
  license "MIT"

  depends_on "node"

  def install
    system "npm", "install", *std_npm_args
    # Always run on Homebrew's Node, whichever version manager is first on PATH.
    (bin/"ided").write_env_script libexec/"bin/ided", PATH: "#{formula_opt_bin("node")}:$PATH"
  end

  def caveats
    <<~EOS
      Connect ided to Claude Code and Codex (skills and MCP server):
        ided setup

      The layout check, screenshots and exports use a pinned Chromium,
      downloaded the first time one needs it (about 100 MB), or now with:
        ided browser install

      Before uninstalling, remove the skills and MCP server from your agents,
      and the downloaded Chromium:
        ided setup --remove
        ided browser remove
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/ided --version")
    system bin/"ided", "init", "--here", "--name", "Brew Test"
    # The layout check measures frames in a browser, which the test sandbox cannot download.
    assert_match "Clean", shell_output("#{bin}/ided check --no-layout")
    system bin/"ided", "export", "brand", "--out", "out"
    assert_path_exists testpath/"out/brew-test-brand-kit/logos/mark/mark-primary.svg"
  end
end
`;
}

if (import.meta.url === `file://${process.argv[1]}`) {
  const { values } = parseArgs({
    options: { version: { type: "string" }, url: { type: "string" }, sha256: { type: "string" }, homepage: { type: "string" } },
  });
  process.stdout.write(formula(values));
}
